# Generated by Django 4.0.4 on 2022-08-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VillaJimena', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedidoproveedoraseojimena',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='detallepedidoproveedorjimena',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='detallepedidoproveedorpersonaljimena',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedoraseojimena',
            name='total_pagado',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedorjimena',
            name='total_pagado',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedorpersonaljimena',
            name='total_pagado',
        ),
    ]
