# Generated by Django 4.0.4 on 2022-08-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VillaJimena', '0002_remove_detallepedidoproveedoraseojimena_precio_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoproveedoraseojimena',
            name='entregado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoproveedoraseojimena',
            name='solicitado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoproveedorjimena',
            name='entregado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoproveedorjimena',
            name='solicitado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoproveedorpersonaljimena',
            name='entregado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoproveedorpersonaljimena',
            name='solicitado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
