# Generated by Django 4.0.4 on 2022-08-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VillaJimena', '0005_alter_pacientevillajimena_segundoapellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientevillajimena',
            name='FechaIngreso',
            field=models.DateField(null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='pacientevillajimena',
            name='FechaNacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
