# Generated by Django 4.0.4 on 2022-08-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VillaJimena', '0006_alter_pacientevillajimena_fechaingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementovillajimena',
            name='fecha_vencimiento',
            field=models.DateField(null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='elementovillajimenaaseo',
            name='fecha_vencimiento',
            field=models.DateField(null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='elementovillajimenapersonal',
            name='fecha_vencimiento',
            field=models.DateField(null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
