# Generated by Django 4.0.4 on 2022-08-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VillaJimena', '0007_alter_elementovillajimena_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientevillajimena',
            name='tallaCalzado',
            field=models.CharField(blank=True, max_length=20, verbose_name='Talla de calzado'),
        ),
        migrations.AlterField(
            model_name='pacientevillajimena',
            name='tallaPrenda',
            field=models.CharField(blank=True, max_length=20, verbose_name='Talla de prenda'),
        ),
    ]
