# Generated by Django 4.0.4 on 2022-08-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VillaJimena', '0008_alter_pacientevillajimena_tallacalzado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementovillajimena',
            name='fechaElemento',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='elementovillajimenaaseo',
            name='fechaElemento',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='elementovillajimenapersonal',
            name='fechaElemento',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso'),
        ),
    ]
