# Generated by Django 4.0.4 on 2022-11-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProveedor', models.CharField(max_length=40, null=True, verbose_name='Nombre')),
                ('NumeroContacto', models.CharField(blank=True, max_length=40, null=True, verbose_name='Número de contacto')),
                ('Correo', models.CharField(blank=True, max_length=40, null=True, verbose_name='Correo')),
                ('Nit', models.IntegerField(null=True, verbose_name='Nit')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
