# Generated by Django 4.0.4 on 2022-05-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorG',
            fields=[
                ('nombreProveedor', models.CharField(max_length=40, verbose_name='Nombre')),
                ('Nit', models.IntegerField(null=True, verbose_name='Nit')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
