# Generated by Django 4.0.4 on 2022-05-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedorg',
            options={'ordering': ['id'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AddField(
            model_name='proveedorg',
            name='Correo',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='proveedorg',
            name='NumeroContacto',
            field=models.CharField(max_length=40, null=True, verbose_name='Número de contacto'),
        ),
        migrations.AlterField(
            model_name='proveedorg',
            name='nombreProveedor',
            field=models.CharField(max_length=40, null=True, verbose_name='Nombre'),
        ),
    ]
