# Generated by Django 4.0.4 on 2022-05-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0002_alter_proveedorg_options_proveedorg_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedorg',
            name='NumeroContacto',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Número de contacto'),
        ),
    ]
