# Generated by Django 4.0.4 on 2022-05-19 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0015_alter_pacientearcoiris_tipodocumento'),
        ('Proveedor', '0003_alter_proveedorg_numerocontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(auto_now=True)),
                ('total_pagado', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedorg')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='DevolucionPedidoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateField(auto_now=True)),
                ('detalle', models.TextField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedorg')),
            ],
            options={
                'verbose_name': 'Devolución pedido',
                'verbose_name_plural': 'Devolución pedido',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cantidad_entregada', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('cantidad_entregada_anterior', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedor.pedidoproveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.elementoarcoiris')),
            ],
            options={
                'verbose_name': 'Detalle pedido',
                'verbose_name_plural': 'Detalle pedido',
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucionPedidoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.DecimalField(decimal_places=2, max_digits=6)),
                ('motivo', models.CharField(choices=[('PM', 'Producto en mal estado'), ('PV', 'Producto vencido')], max_length=2)),
                ('devolucion_pedido_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedor.devolucionpedidoproveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.elementoarcoiris')),
            ],
            options={
                'verbose_name': 'Detalle devolución',
                'verbose_name_plural': 'Detalle devolución',
            },
        ),
    ]
