# Generated by Django 4.0.4 on 2022-05-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0004_pedidoproveedor_devolucionpedidoproveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedidoproveedor',
            name='cantidad_entregada',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedor',
            name='cantidad_entregada_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedor',
            name='cantidad_solicitada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedor',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedidoproveedor',
            name='total_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
