# Generated by Django 4.0.4 on 2022-05-25 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0005_alter_detallepedidoproveedor_cantidad_entregada_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProveedorG',
            new_name='Proveedor',
        ),
    ]
