# Generated by Django 4.0.4 on 2022-05-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0006_rename_proveedorg_proveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
