# Generated by Django 4.0.4 on 2022-05-31 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0020_elementoarcoiris_unidadmedida_and_more'),
        ('Proveedor', '0008_alter_detallepedidoproveedor_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedidoproveedor',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.elementoarcoiris'),
        ),
    ]
