# Generated by Django 4.0.4 on 2022-06-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0009_alter_detallepedidoproveedor_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedidoproveedor',
            options={'verbose_name': 'DETALLE PEDIDO', 'verbose_name_plural': 'DETALLE PEDIDO'},
        ),
    ]
