# Generated by Django 4.0.4 on 2022-06-05 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0010_alter_detallepedidoproveedor_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedidoproveedor',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='detallepedidoproveedor',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='devolucionpedidoproveedor',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedor',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='DetalleDevolucionPedidoProveedor',
        ),
        migrations.DeleteModel(
            name='DetallePedidoProveedor',
        ),
        migrations.DeleteModel(
            name='DevolucionPedidoProveedor',
        ),
        migrations.DeleteModel(
            name='PedidoProveedor',
        ),
    ]
