# Generated by Django 4.0.4 on 2022-06-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0011_remove_detallepedidoproveedor_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
