# Generated by Django 4.0.4 on 2022-05-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0002_alter_elementos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementos',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Elemento'),
        ),
    ]
