# Generated by Django 4.0.4 on 2022-05-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0006_alter_elementos_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDiscapacidad', models.CharField(max_length=40, verbose_name='Discapacidad')),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimerApellido', models.CharField(max_length=40, verbose_name='Primer apellido')),
                ('SegundoApellido', models.CharField(max_length=40, verbose_name='Segundo apellido')),
                ('PrimerNombre', models.CharField(max_length=40, verbose_name='Primer nombre')),
                ('SegundoNombre', models.CharField(max_length=40, verbose_name='Segundo nombre')),
                ('FechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('NumeroDocumento', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('FechaIngreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('FechaEgreso', models.DateField(verbose_name='Fecha de salida')),
            ],
        ),
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSede', models.CharField(max_length=60, verbose_name='Nombre de la sede')),
                ('direccionSede', models.CharField(max_length=80, verbose_name='Dirección')),
            ],
        ),
        migrations.RenameField(
            model_name='elementos',
            old_name='descripcion',
            new_name='descripcionElemento',
        ),
        migrations.RenameField(
            model_name='elementos',
            old_name='fecha',
            new_name='fechaElemento',
        ),
        migrations.RenameField(
            model_name='elementos',
            old_name='nombre',
            new_name='nombreElemento',
        ),
    ]
