# Generated by Django 4.0.4 on 2022-05-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0010_delete_discapacidad_delete_sedes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='TipoDocumento',
            field=models.CharField(choices=[('CC', 'CC'), ('RC', 'RC'), ('TI', ' TI')], default='F', max_length=40, verbose_name='Tipo de cédula'),
        ),
    ]
