# Generated by Django 4.0.4 on 2022-05-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0011_alter_pacientes_tipodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='TipoDocumento',
            field=models.CharField(choices=[('CC', 'C.C'), ('RC', 'R.C'), ('TI', ' T.I')], default='F', max_length=40, verbose_name='Tipo de cédula'),
        ),
    ]
