# Generated by Django 4.0.4 on 2022-05-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0013_alter_pacientes_fechaegreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='FechaIngreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso'),
        ),
    ]
