# Generated by Django 4.0.4 on 2022-05-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0015_pacientes_discapacidad_pacientes_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='sede',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='Unidad',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Unidad'),
        ),
    ]
