# Generated by Django 4.0.4 on 2022-05-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0016_remove_pacientes_sede_pacientes_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProveedor', models.CharField(max_length=40, verbose_name='Nombre')),
                ('Nit', models.IntegerField(null=True, verbose_name='Nit')),
            ],
        ),
        migrations.AddField(
            model_name='elementos',
            name='cantidad',
            field=models.IntegerField(null=True, verbose_name='Cantidad'),
        ),
    ]
