# Generated by Django 4.0.4 on 2022-05-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0019_rename_elementos_elemento_delete_pacientes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
