# Generated by Django 4.0.4 on 2022-05-17 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0021_elemento_tipoproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Elemento',
        ),
    ]
