# Generated by Django 4.0.4 on 2022-05-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VillaAdriana', '0004_remove_elementovillaadriana_tipoproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementovillaadriana',
            name='descripcionElemento',
        ),
        migrations.AlterField(
            model_name='pacientevillaadriana',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='g', max_length=40, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='pacientevillaadriana',
            name='modalidad',
            field=models.CharField(choices=[('PSICO', ' Psicosocial'), ('INTELE', 'Intelectual')], default='a', max_length=40, verbose_name='Modalidad'),
        ),
    ]
