# Generated by Django 4.0.4 on 2022-05-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VillaAdriana', '0005_remove_elementovillaadriana_descripcionelemento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoVillaadrianaAseo',
            fields=[
                ('nombreElemento', models.CharField(max_length=100, verbose_name='Elemento')),
                ('fechaElemento', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('cantidad', models.IntegerField(null=True, verbose_name='Cantidad')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Dotación Aseo Personal',
                'verbose_name_plural': 'Dotación aseo personal',
                'ordering': ['nombreElemento'],
            },
        ),
        migrations.CreateModel(
            name='ElementoVillaadrianaPersonal',
            fields=[
                ('nombreElemento', models.CharField(max_length=100, verbose_name='Elemento')),
                ('fechaElemento', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('cantidad', models.IntegerField(null=True, verbose_name='Cantidad')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(blank=True, max_length=40, null=True, verbose_name='Talla')),
                ('descripcionElemento', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
