# Generated by Django 4.0.4 on 2022-05-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VillaAdriana', '0010_alter_pacientevillaadriana_tipodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementovillaadriana',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='elementovillaadrianaaseo',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='elementovillaadrianapersonal',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
