# Generated by Django 4.0.4 on 2022-05-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VillaAdriana', '0012_alter_elementovillaadrianapersonal_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementovillaadriana',
            old_name='cantidad',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='elementovillaadrianaaseo',
            old_name='cantidad',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='elementovillaadrianapersonal',
            old_name='cantidad',
            new_name='stock',
        ),
    ]
