# Generated by Django 4.0.4 on 2022-06-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VillaAdriana', '0016_alter_pacientevillaadriana_tiposalida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementovillaadriana',
            name='stock',
            field=models.IntegerField(default=10, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='elementovillaadrianaaseo',
            name='stock',
            field=models.IntegerField(default=10, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='elementovillaadrianapersonal',
            name='stock',
            field=models.IntegerField(default=10, null=True, verbose_name='Cantidad'),
        ),
    ]
