# Generated by Django 4.0.4 on 2022-08-02 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0012_alter_proveedor_id'),
        ('VillaAdriana', '0017_alter_elementovillaadriana_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaDotacionPersonalFORMAdriana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitado_por', models.CharField(blank=True, max_length=40, null=True, verbose_name='Solicitado por:')),
                ('unidad', models.CharField(blank=True, default='Arco Iris', max_length=24, null=True, verbose_name='Unidad')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaAdriana.pacientevillaadriana')),
            ],
            options={
                'verbose_name': 'Salida Dotación Personal',
                'verbose_name_plural': 'Salidas Dotación Personal',
            },
        ),
        migrations.CreateModel(
            name='PedidoProveedorPersonalAdriana',
            fields=[
                ('cantidad_solicitada', models.IntegerField(default=0)),
                ('cantidad_entregada', models.IntegerField(blank=True, default=0)),
                ('cantidad_entregada_anterior', models.IntegerField(blank=True, default=0)),
                ('fecha_pedido', models.DateField(auto_now=True, verbose_name='Fecha de solicitud')),
                ('fecha_solicitud', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('solicitadoo', models.CharField(blank=True, max_length=40, null=True, verbose_name='Solicitado por:')),
                ('recibido', models.CharField(blank=True, max_length=40, null=True, verbose_name='Recibido por:')),
                ('entregado', models.BooleanField(blank=True, null=True)),
                ('solicitado', models.BooleanField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pagado', models.IntegerField(blank=True, default=0)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaAdriana.elementovillaadrianapersonal')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Pedido de dotación personal',
                'verbose_name_plural': 'Pedidos de dotación personal',
            },
        ),
        migrations.CreateModel(
            name='PedidoProveedorAseoAdriana',
            fields=[
                ('cantidad_solicitada', models.IntegerField(default=0)),
                ('cantidad_entregada', models.IntegerField(blank=True, default=0)),
                ('cantidad_entregada_anterior', models.IntegerField(blank=True, default=0)),
                ('fecha_pedido', models.DateField(auto_now=True, verbose_name='Fecha de solicitud')),
                ('fecha_solicitud', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('solicitadoo', models.CharField(blank=True, max_length=40, null=True, verbose_name='Solicitado por:')),
                ('recibido', models.CharField(blank=True, max_length=40, null=True, verbose_name='Recibido por:')),
                ('entregado', models.BooleanField(blank=True, null=True)),
                ('solicitado', models.BooleanField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pagado', models.IntegerField(blank=True, default=0)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaAdriana.elementovillaadrianaaseo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Pedido dotación de aseo personal ',
                'verbose_name_plural': 'Pedidos de aseo personal',
            },
        ),
        migrations.CreateModel(
            name='PedidoProveedorAdriana',
            fields=[
                ('cantidad_solicitada', models.IntegerField(default=0)),
                ('cantidad_entregada', models.IntegerField(blank=True, default=0)),
                ('cantidad_entregada_anterior', models.IntegerField(blank=True, default=0)),
                ('fecha_pedido', models.DateField(auto_now=True, verbose_name='Fecha de solicitud')),
                ('fecha_solicitud', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('solicitadoo', models.CharField(blank=True, max_length=40, null=True, verbose_name='Solicitado por:')),
                ('recibido', models.CharField(blank=True, max_length=40, null=True, verbose_name='Recibido por:')),
                ('entregado', models.BooleanField(blank=True, null=True)),
                ('solicitado', models.BooleanField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pagado', models.IntegerField(blank=True, default=0)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaAdriana.elementovillaadriana')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Pedido de dotación dormitorio',
                'verbose_name_plural': 'Pedidos de dotación dormitorio',
            },
        ),
        migrations.CreateModel(
            name='DevolucionPedidoProveedorPersonalAdriana',
            fields=[
                ('fecha_devolucion', models.DateField(auto_now=True)),
                ('detalle', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Devolución pedido',
                'verbose_name_plural': 'Devoluciones pedido de dotación personal',
            },
        ),
        migrations.CreateModel(
            name='DevolucionPedidoProveedorAseoAdriana',
            fields=[
                ('fecha_devolucion', models.DateField(auto_now=True)),
                ('detalle', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Devolución pedido',
                'verbose_name_plural': 'Devoluciones pedido de aseo personal ',
            },
        ),
        migrations.CreateModel(
            name='DevolucionPedidoProveedorAdriana',
            fields=[
                ('fecha_devolucion', models.DateField(auto_now=True)),
                ('detalle', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Devolución pedido',
                'verbose_name_plural': 'Devoluciones pedido de dotación dormitorio',
            },
        ),
        migrations.CreateModel(
            name='DetalleSalidaDotaciónPersonalAdriana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('especificacion', models.CharField(choices=[('REPOSICIÓN POR ROTO', 'REPOSICIÓN POR ROTO'), ('REPOSICIÓN POR DETERIORO', 'REPOSICIÓN POR DETERIORO')], max_length=24, verbose_name='Especificación')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaAdriana.elementovillaadrianapersonal')),
                ('salida_dotacion_personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaAdriana.salidadotacionpersonalformadriana')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaAdriana.pacientevillaadriana')),
            ],
            options={
                'verbose_name': 'DETALLE SALIDA',
                'verbose_name_plural': 'DETALLE SALIDA',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoProveedorPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField(default=0)),
                ('cantidad_entregada', models.IntegerField(blank=True, default=0)),
                ('cantidad_entregada_anterior', models.IntegerField(blank=True, default=0)),
                ('precio_compra', models.IntegerField(default=0)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaAdriana.pedidoproveedorpersonaladriana')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaAdriana.elementovillaadrianapersonal')),
            ],
            options={
                'verbose_name': 'DETALLE DE PEDIDO PARA DOTACIÓN PERSONAL',
                'verbose_name_plural': 'DETALLE DE PEDIDO PARA DOTACIÓN PERSONAL',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoProveedorAseoAdriana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField(default=0)),
                ('cantidad_entregada', models.IntegerField(blank=True, default=0)),
                ('cantidad_entregada_anterior', models.IntegerField(blank=True, default=0)),
                ('precio_compra', models.IntegerField(default=0)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaAdriana.pedidoproveedoraseoadriana')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaAdriana.elementovillaadrianaaseo')),
            ],
            options={
                'verbose_name': 'DETALLE DE PEDIDO PARA DOTACIÓN DE ASEO PERSONAL',
                'verbose_name_plural': 'DETALLE DE PEDIDO PARA DOTACIÓN DE ASEO PERSONAL',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoProveedorAdriana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField(default=0)),
                ('cantidad_entregada', models.IntegerField(blank=True, default=0)),
                ('cantidad_entregada_anterior', models.IntegerField(blank=True, default=0)),
                ('precio_compra', models.IntegerField(default=0)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaAdriana.pedidoproveedoradriana')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaAdriana.elementovillaadriana')),
            ],
            options={
                'verbose_name': 'DETALLE DE PEDIDO PARA DOTACIÓN DE DORMITORIO',
                'verbose_name_plural': 'DETALLE DE PEDIDO PARA DOTACIÓN DE DORMITORIO',
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucionPedidoProveedorPersonalAdriana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.IntegerField()),
                ('motivo', models.CharField(choices=[('PM', 'Producto en mal estado'), ('PV', 'Producto vencido')], max_length=2)),
                ('devolucion_pedido_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaAdriana.devolucionpedidoproveedorpersonaladriana')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaAdriana.elementovillaadrianapersonal')),
            ],
            options={
                'verbose_name': 'Detalle devolución',
                'verbose_name_plural': 'Detalle devolución',
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucionPedidoProveedorAseoAdriana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.IntegerField()),
                ('motivo', models.CharField(choices=[('PM', 'Producto en mal estado'), ('PV', 'Producto vencido')], max_length=2)),
                ('devolucion_pedido_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaAdriana.devolucionpedidoproveedoraseoadriana')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaAdriana.elementovillaadrianaaseo')),
            ],
            options={
                'verbose_name': 'Detalle devolución',
                'verbose_name_plural': 'Detalle devolución',
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucionPedidoProveedorAdriana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.IntegerField()),
                ('motivo', models.CharField(choices=[('PM', 'Producto en mal estado'), ('PV', 'Producto vencido')], max_length=2)),
                ('devolucion_pedido_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaAdriana.devolucionpedidoproveedoradriana')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaAdriana.elementovillaadriana')),
            ],
            options={
                'verbose_name': 'Detalle devolución',
                'verbose_name_plural': 'Detalle devolución',
            },
        ),
    ]
