# Generated by Django 4.0.4 on 2022-08-02 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VillaAdriana', '0018_salidadotacionpersonalformadriana_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetallePedidoProveedorPersonal',
            new_name='DetallePedidoProveedorPersonalAdriana',
        ),
    ]
