# Generated by Django 4.0.4 on 2022-08-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VillaAdriana', '0019_rename_detallepedidoproveedorpersonal_detallepedidoproveedorpersonaladriana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedidoproveedoradriana',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='detallepedidoproveedoraseoadriana',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='detallepedidoproveedorpersonaladriana',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedoradriana',
            name='total_pagado',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedoraseoadriana',
            name='total_pagado',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedorpersonaladriana',
            name='total_pagado',
        ),
    ]
