# Generated by Django 4.0.4 on 2022-08-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VillaAdriana', '0020_remove_detallepedidoproveedoradriana_precio_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoproveedoradriana',
            name='entregado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoproveedoradriana',
            name='solicitado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoproveedoraseoadriana',
            name='entregado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoproveedoraseoadriana',
            name='solicitado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoproveedorpersonaladriana',
            name='entregado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoproveedorpersonaladriana',
            name='solicitado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
