# Generated by Django 4.0.4 on 2022-05-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoArcoiris',
            fields=[
                ('nombreElemento', models.CharField(max_length=100, verbose_name='Elemento')),
                ('fechaElemento', models.DateField(verbose_name='Fecha de creación')),
                ('descripcionElemento', models.TextField(null=True, verbose_name='Descripción')),
                ('cantidad', models.IntegerField(null=True, verbose_name='Cantidad')),
                ('TipoProducto', models.CharField(blank=True, choices=[('Dormitorio', 'Dormitorio'), ('UsoPersonal', 'Uso personal'), ('UsoComún', 'Uso común')], default='F', max_length=40, null=True, verbose_name='Tipo de cédula')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
                'ordering': ['id'],
            },
        ),
    ]
