# Generated by Django 4.0.4 on 2022-05-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0004_remove_elementoarcoiris_tipoproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementoarcoiris',
            options={'ordering': ['nombreElemento'], 'verbose_name': 'Dotación Dormitorio', 'verbose_name_plural': 'Elementos'},
        ),
    ]
