# Generated by Django 4.0.4 on 2022-05-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0006_elementoarcoirisaseo_alter_elementoarcoiris_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElementoArcoirisAseo',
        ),
    ]
