# Generated by Django 4.0.4 on 2022-05-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0007_delete_elementoarcoirisaseo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoArcoirisAseo',
            fields=[
                ('nombreElemento', models.CharField(max_length=100, verbose_name='Elemento')),
                ('fechaElemento', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('descripcionElemento', models.TextField(null=True, verbose_name='Descripción')),
                ('cantidad', models.IntegerField(null=True, verbose_name='Cantidad')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Dotación Aseo Personal',
                'verbose_name_plural': 'Dotación Aseo Personal',
                'ordering': ['nombreElemento'],
            },
        ),
    ]
