# Generated by Django 4.0.4 on 2022-05-17 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0008_elementoarcoirisaseo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElementoArcoirisAseo',
        ),
    ]
