# Generated by Django 4.0.4 on 2022-05-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0010_elementoarcoirisaseo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoArcoirisPersonal',
            fields=[
                ('nombreElemento', models.CharField(max_length=100, verbose_name='Elemento')),
                ('fechaElemento', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('cantidad', models.IntegerField(null=True, verbose_name='Cantidad')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(blank=True, max_length=40, null=True, verbose_name='Talla')),
                ('descripcionElemento', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='elementoarcoiris',
            name='descripcionElemento',
        ),
        migrations.RemoveField(
            model_name='elementoarcoirisaseo',
            name='descripcionElemento',
        ),
        migrations.AlterField(
            model_name='pacientearcoiris',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='g', max_length=40, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='pacientearcoiris',
            name='modalidad',
            field=models.CharField(choices=[('PSICO', ' Psicosocial'), ('INTELE', 'Intelectual')], default='a', max_length=40, verbose_name='Modalidad'),
        ),
    ]
