# Generated by Django 4.0.4 on 2022-05-17 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0011_elementoarcoirispersonal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementoarcoiris',
            options={'ordering': ['nombreElemento'], 'verbose_name': 'Dotación Dormitorio', 'verbose_name_plural': 'Dotación dormitorio'},
        ),
        migrations.AlterModelOptions(
            name='elementoarcoirisaseo',
            options={'ordering': ['nombreElemento'], 'verbose_name': 'Dotación Aseo Personal', 'verbose_name_plural': 'Dotación aseo personal'},
        ),
    ]
