# Generated by Django 4.0.4 on 2022-05-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0013_alter_elementoarcoirispersonal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementoarcoiris',
            name='nombreElemento',
            field=models.CharField(max_length=100, null=True, verbose_name='Elemento'),
        ),
        migrations.AlterField(
            model_name='elementoarcoirisaseo',
            name='nombreElemento',
            field=models.CharField(max_length=100, null=True, verbose_name='Elemento'),
        ),
        migrations.AlterField(
            model_name='elementoarcoirispersonal',
            name='nombreElemento',
            field=models.CharField(max_length=100, null=True, verbose_name='Elemento'),
        ),
        migrations.AlterField(
            model_name='pacientearcoiris',
            name='FechaNacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='pacientearcoiris',
            name='PrimerApellido',
            field=models.CharField(max_length=40, null=True, verbose_name='Primer apellido'),
        ),
        migrations.AlterField(
            model_name='pacientearcoiris',
            name='TipoDocumento',
            field=models.CharField(choices=[('CC', 'C.C'), ('RC', 'R.C'), ('TI', ' T.I')], default='F', max_length=40, null=True, verbose_name='Tipo de cédula'),
        ),
        migrations.AlterField(
            model_name='pacientearcoiris',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='g', max_length=40, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='pacientearcoiris',
            name='modalidad',
            field=models.CharField(choices=[('PSICO', ' Psicosocial'), ('INTELE', 'Intelectual')], default='a', max_length=40, null=True, verbose_name='Modalidad'),
        ),
    ]
