# Generated by Django 4.0.4 on 2022-05-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0017_alter_elementoarcoirispersonal_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementoarcoiris',
            old_name='cantidad',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='elementoarcoirisaseo',
            old_name='cantidad',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='elementoarcoirispersonal',
            old_name='cantidad',
            new_name='stock',
        ),
    ]
