# Generated by Django 4.0.4 on 2022-06-05 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0011_remove_detallepedidoproveedor_pedido_and_more'),
        ('ArcoIris', '0020_elementoarcoiris_unidadmedida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(auto_now=True)),
                ('total_pagado', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='DevolucionPedidoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateField(auto_now=True)),
                ('detalle', models.TextField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Devolución pedido',
                'verbose_name_plural': 'Devolución pedido',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_entregada', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('cantidad_entregada_anterior', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.pedidoproveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.elementoarcoiris')),
            ],
            options={
                'verbose_name': 'DETALLE PEDIDO',
                'verbose_name_plural': 'DETALLE PEDIDO',
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucionPedidoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.DecimalField(decimal_places=2, max_digits=6)),
                ('motivo', models.CharField(choices=[('PM', 'Producto en mal estado'), ('PV', 'Producto vencido')], max_length=2)),
                ('devolucion_pedido_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.devolucionpedidoproveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.elementoarcoiris')),
            ],
            options={
                'verbose_name': 'Detalle devolución',
                'verbose_name_plural': 'Detalle devolución',
            },
        ),
    ]
