# Generated by Django 4.0.4 on 2022-06-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0022_detallepedidoproveedorpersonal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedidoproveedor',
            options={'verbose_name': 'DETALLE DE PEDIDO PARA DOTACIÓN DE DORMITORIO', 'verbose_name_plural': 'DETALLE DE PEDIDO PARA DOTACIÓN DE DORMITORIO'},
        ),
        migrations.AlterModelOptions(
            name='detallepedidoproveedoraseo',
            options={'verbose_name': 'DETALLE DE PEDIDO PARA DOTACIÓN DE ASEO PERSONAL', 'verbose_name_plural': 'DETALLE DE PEDIDO PARA DOTACIÓN DE ASEO PERSONAL'},
        ),
        migrations.AlterModelOptions(
            name='detallepedidoproveedorpersonal',
            options={'verbose_name': 'DETALLE DE PEDIDO PARA DOTACIÓN PERSONAL', 'verbose_name_plural': 'DETALLE DE PEDIDO PARA DOTACIÓN PERSONAL'},
        ),
    ]
