# Generated by Django 4.0.4 on 2022-06-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0024_rename_producto_detallepedidoproveedoraseo_productoa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedidoproveedoraseo',
            old_name='productoA',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='detallepedidoproveedorpersonal',
            old_name='productoP',
            new_name='producto',
        ),
    ]
