# Generated by Django 4.0.4 on 2022-06-06 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0026_alter_detalledevolucionpedidoproveedor_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledevolucionpedidoproveedor',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.elementoarcoiris'),
        ),
    ]
