# Generated by Django 4.0.4 on 2022-06-08 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0011_remove_detallepedidoproveedor_pedido_and_more'),
        ('ArcoIris', '0027_alter_detalledevolucionpedidoproveedor_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproveedor',
            name='cantidad_entregada',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='cantidad_entregada_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='cantidad_solicitada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.elementoarcoiris'),
        ),
        migrations.AlterField(
            model_name='detalledevolucionpedidoproveedor',
            name='devolucion_pedido_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.devolucionpedidoproveedor'),
        ),
        migrations.AlterField(
            model_name='detalledevolucionpedidoproveedor',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.elementoarcoiris'),
        ),
        migrations.AlterField(
            model_name='detalledevolucionpedidoproveedoraseo',
            name='devolucion_pedido_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.devolucionpedidoproveedor'),
        ),
        migrations.AlterField(
            model_name='detalledevolucionpedidoproveedoraseo',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.elementoarcoirisaseo'),
        ),
        migrations.AlterField(
            model_name='detalledevolucionpedidoproveedorpersonal',
            name='devolucion_pedido_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.devolucionpedidoproveedor'),
        ),
        migrations.AlterField(
            model_name='detalledevolucionpedidoproveedorpersonal',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.elementoarcoirispersonal'),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedor',
            name='cantidad_entregada',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedor',
            name='cantidad_entregada_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedor',
            name='cantidad_solicitada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedor',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.pedidoproveedor'),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedor',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.elementoarcoiris'),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedoraseo',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.pedidoproveedor'),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedoraseo',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.elementoarcoirisaseo'),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedorpersonal',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.pedidoproveedor'),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedorpersonal',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.elementoarcoirispersonal'),
        ),
        migrations.AlterField(
            model_name='devolucionpedidoproveedor',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor'),
        ),
        migrations.AlterField(
            model_name='pedidoproveedor',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor'),
        ),
    ]
