# Generated by Django 4.0.4 on 2022-06-08 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0031_detallepedidoproveedor_producto2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedidoproveedor',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedor',
            name='producto',
        ),
    ]
