# Generated by Django 4.0.4 on 2022-06-08 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0032_remove_detallepedidoproveedor_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedidoproveedor',
            old_name='producto2',
            new_name='Producto',
        ),
        migrations.RenameField(
            model_name='pedidoproveedor',
            old_name='producto2',
            new_name='Producto',
        ),
    ]
