# Generated by Django 4.0.4 on 2022-06-08 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0034_rename_producto_detallepedidoproveedor_producto2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedidoproveedor',
            old_name='producto2',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='pedidoproveedor',
            old_name='producto2',
            new_name='producto',
        ),
        migrations.RemoveField(
            model_name='detallepedidoproveedor',
            name='producto1',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedor',
            name='producto1',
        ),
    ]
