# Generated by Django 4.0.4 on 2022-06-09 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0011_remove_detallepedidoproveedor_pedido_and_more'),
        ('ArcoIris', '0035_rename_producto2_detallepedidoproveedor_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoProveedorAseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_entregada', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('cantidad_entregada_anterior', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('fecha_pedido', models.DateField(auto_now=True)),
                ('total_pagado', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.elementoarcoirisaseo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Pedido dotación de aseo personal ',
                'verbose_name_plural': 'Pedidos de aseo personal',
            },
        ),
        migrations.CreateModel(
            name='PedidoProveedorPersonal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_entregada', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('cantidad_entregada_anterior', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('fecha_pedido', models.DateField(auto_now=True)),
                ('total_pagado', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.elementoarcoirispersonal')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Pedido de dotación personal',
                'verbose_name_plural': 'Pedidos de dotación personal',
            },
        ),
        migrations.RemoveField(
            model_name='detalledevolucionpedidoproveedorpersonal',
            name='devolucion_pedido_proveedor',
        ),
        migrations.RemoveField(
            model_name='detalledevolucionpedidoproveedorpersonal',
            name='producto',
        ),
        migrations.AlterModelOptions(
            name='pedidoproveedor',
            options={'verbose_name': 'Pedido de dotación dormitorio', 'verbose_name_plural': 'Pedidos de dotación dormitorio'},
        ),
        migrations.DeleteModel(
            name='DetalleDevolucionPedidoProveedorAseo',
        ),
        migrations.DeleteModel(
            name='DetalleDevolucionPedidoProveedorPersonal',
        ),
    ]
