# Generated by Django 4.0.4 on 2022-06-09 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0036_pedidoproveedoraseo_pedidoproveedorpersonal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedidoproveedoraseo',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.pedidoproveedoraseo'),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedorpersonal',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.pedidoproveedorpersonal'),
        ),
    ]
