# Generated by Django 4.0.4 on 2022-06-09 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0037_alter_detallepedidoproveedoraseo_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedidoproveedor',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.elementoarcoiris'),
        ),
        migrations.AlterField(
            model_name='pedidoproveedor',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.elementoarcoiris'),
        ),
    ]
