# Generated by Django 4.0.4 on 2022-06-09 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0038_alter_detallepedidoproveedor_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledevolucionpedidoproveedor',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.elementoarcoirisaseo'),
        ),
    ]
