# Generated by Django 4.0.4 on 2022-06-09 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0011_remove_detallepedidoproveedor_pedido_and_more'),
        ('ArcoIris', '0040_alter_detalledevolucionpedidoproveedor_producto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devolucionpedidoproveedor',
            options={'verbose_name': 'Devolución pedido', 'verbose_name_plural': 'Devoluciones pedido de dotación dormitorio'},
        ),
        migrations.CreateModel(
            name='DevolucionPedidoProveedorPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateField(auto_now=True)),
                ('detalle', models.TextField()),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Devolución pedido',
                'verbose_name_plural': 'Devoluciones pedido de dotación personal',
            },
        ),
        migrations.CreateModel(
            name='DevolucionPedidoProveedorAseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateField(auto_now=True)),
                ('detalle', models.TextField()),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Devolución pedido',
                'verbose_name_plural': 'Devoluciones pedido de aseo personal ',
            },
        ),
        migrations.AlterField(
            model_name='detalledevolucionpedidoproveedoraseo',
            name='devolucion_pedido_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.devolucionpedidoproveedoraseo'),
        ),
        migrations.AlterField(
            model_name='detalledevolucionpedidoproveedorpersonal',
            name='devolucion_pedido_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.devolucionpedidoproveedorpersonal'),
        ),
    ]
