# Generated by Django 4.0.4 on 2022-06-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0042_alter_devolucionpedidoproveedor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproveedor',
            name='total_pagado',
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoproveedor',
            name='fecha_pedido',
            field=models.DateField(auto_now=True, verbose_name='Fecha de solicitud'),
        ),
    ]
