# Generated by Django 4.0.4 on 2022-06-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0043_remove_pedidoproveedor_total_pagado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproveedor',
            name='total_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
