# Generated by Django 4.0.4 on 2022-06-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0044_pedidoproveedor_total_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproveedor',
            name='recibido',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Recibido por:'),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='solicitado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Solicitado por:'),
        ),
    ]
