# Generated by Django 4.0.4 on 2022-06-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0045_pedidoproveedor_recibido_pedidoproveedor_solicitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproveedoraseo',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pedido'),
        ),
        migrations.AddField(
            model_name='pedidoproveedoraseo',
            name='recibido',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Recibido por:'),
        ),
        migrations.AddField(
            model_name='pedidoproveedoraseo',
            name='solicitado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Solicitado por:'),
        ),
        migrations.AddField(
            model_name='pedidoproveedorpersonal',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pedido'),
        ),
        migrations.AddField(
            model_name='pedidoproveedorpersonal',
            name='recibido',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Recibido por:'),
        ),
        migrations.AddField(
            model_name='pedidoproveedorpersonal',
            name='solicitado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Solicitado por:'),
        ),
    ]
