# Generated by Django 4.0.4 on 2022-06-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0046_pedidoproveedoraseo_fecha_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoproveedoraseo',
            name='fecha_pedido',
            field=models.DateField(auto_now=True, verbose_name='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='pedidoproveedorpersonal',
            name='fecha_pedido',
            field=models.DateField(auto_now=True, verbose_name='Fecha de solicitud'),
        ),
    ]
