# Generated by Django 4.0.4 on 2022-06-27 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0047_alter_pedidoproveedoraseo_fecha_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedidoproveedorpersonal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedidoproveedor',
            name='fecha_solicitud',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pedido:(cantidad de entrega)'),
        ),
        migrations.AlterField(
            model_name='pedidoproveedor',
            name='recibido',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Recibido por:'),
        ),
        migrations.AlterField(
            model_name='pedidoproveedor',
            name='solicitado',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Solicitado por:'),
        ),
        migrations.AlterField(
            model_name='pedidoproveedoraseo',
            name='recibido',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Recibido por:'),
        ),
        migrations.AlterField(
            model_name='pedidoproveedoraseo',
            name='solicitado',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Solicitado por:'),
        ),
        migrations.AlterField(
            model_name='pedidoproveedorpersonal',
            name='recibido',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Recibido por:'),
        ),
        migrations.AlterField(
            model_name='pedidoproveedorpersonal',
            name='solicitado',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Solicitado por:'),
        ),
        migrations.CreateModel(
            name='SalidaDotacionPersonalFORM',
            fields=[
                ('solicitado_por', models.CharField(max_length=40, verbose_name='Solicitado por:')),
                ('unidad', models.CharField(choices=[('VILLA ADRIANA', 'Villa Adriana'), ('VILLA BLANCA', 'Villa Blanca'), ('VILLA JIMENA', ' Villa Jimena'), ('ARCO IRIS', 'Arco Iris')], max_length=24, verbose_name='Unidad')),
                ('Fecha', models.DateField(verbose_name='Fecha')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.pacientearcoiris')),
            ],
            options={
                'verbose_name': 'Salida Dotación Personal',
                'verbose_name_plural': 'Salidas Dotación Personal',
            },
        ),
        migrations.CreateModel(
            name='DetalleSalidaDotaciónPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('especificación', models.CharField(choices=[('REPOSICIÓN POR ROTO', 'REPOSICIÓN POR ROTO'), ('REPOSICIÓN POR DETERIORO', 'REPOSICIÓN POR DETERIORO')], max_length=24)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.elementoarcoirispersonal')),
                ('salida_dotacion_personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.salidadotacionpersonalform')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArcoIris.pacientearcoiris')),
            ],
            options={
                'verbose_name': 'Detalle salida',
                'verbose_name_plural': 'Detalle salida',
            },
        ),
    ]
