# Generated by Django 4.0.4 on 2022-06-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0048_alter_detallepedidoproveedorpersonal_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salidadotacionpersonalform',
            old_name='Fecha',
            new_name='fecha',
        ),
        migrations.AlterField(
            model_name='detallesalidadotaciónpersonal',
            name='especificación',
            field=models.CharField(choices=[('REPOSICIÓN POR ROTO', 'REPOSICIÓN POR ROTO'), ('REPOSICIÓN POR DETERIORO', 'REPOSICIÓN POR DETERIORO')], max_length=24, verbose_name='Especificación'),
        ),
    ]
