# Generated by Django 4.0.4 on 2022-06-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0050_alter_pacientearcoiris_tiposalida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementoarcoiris',
            name='stock',
            field=models.IntegerField(default=10, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='elementoarcoirisaseo',
            name='stock',
            field=models.IntegerField(default=10, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='elementoarcoirispersonal',
            name='stock',
            field=models.IntegerField(default=10, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='salidadotacionpersonalform',
            name='unidad',
            field=models.CharField(default='Arco Iris', max_length=24, verbose_name='Unidad'),
        ),
    ]
