# Generated by Django 4.0.4 on 2022-06-28 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0051_alter_elementoarcoiris_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallesalidadotaciónpersonal',
            options={'verbose_name': 'DETALLE SALIDA', 'verbose_name_plural': 'DETALLE SALIDA'},
        ),
        migrations.RenameField(
            model_name='detallesalidadotaciónpersonal',
            old_name='especificación',
            new_name='especificacion',
        ),
    ]
