# Generated by Django 4.0.4 on 2022-07-06 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0053_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidadotacionpersonalform',
            name='usuario',
        ),
    ]
