# Generated by Django 4.0.4 on 2022-07-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0055_delete_person_salidadotacionpersonalform_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidadotacionpersonalform',
            name='fecha',
            field=models.DateField(auto_now=True, verbose_name='Fecha'),
        ),
    ]
