# Generated by Django 4.0.4 on 2022-07-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0056_alter_salidadotacionpersonalform_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidadotacionpersonalform',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
