# Generated by Django 4.0.4 on 2022-07-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0057_alter_salidadotacionpersonalform_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidadotacionpersonalform',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
