# Generated by Django 4.0.4 on 2022-07-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0058_alter_salidadotacionpersonalform_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesalidadotaciónpersonal',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='detallesalidadotaciónpersonal',
            name='solicitado_por',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Solicitado por:'),
        ),
        migrations.AddField(
            model_name='detallesalidadotaciónpersonal',
            name='unidad',
            field=models.CharField(blank=True, default='Arco Iris', max_length=24, null=True, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='salidadotacionpersonalform',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='salidadotacionpersonalform',
            name='solicitado_por',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Solicitado por:'),
        ),
        migrations.AlterField(
            model_name='salidadotacionpersonalform',
            name='unidad',
            field=models.CharField(blank=True, default='Arco Iris', max_length=24, null=True, verbose_name='Unidad'),
        ),
    ]
