# Generated by Django 4.0.4 on 2022-07-14 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0059_detallesalidadotaciónpersonal_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesalidadotaciónpersonal',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='detallesalidadotaciónpersonal',
            name='solicitado_por',
        ),
        migrations.RemoveField(
            model_name='detallesalidadotaciónpersonal',
            name='unidad',
        ),
    ]
