# Generated by Django 4.0.4 on 2022-07-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0060_remove_detallesalidadotaciónpersonal_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledevolucionpedidoproveedor',
            name='cantidad_devuelta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detalledevolucionpedidoproveedoraseo',
            name='cantidad_devuelta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detalledevolucionpedidoproveedorpersonal',
            name='cantidad_devuelta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedor',
            name='cantidad_entregada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedor',
            name='cantidad_entregada_anterior',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedor',
            name='cantidad_solicitada',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedor',
            name='precio_compra',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedoraseo',
            name='cantidad_entregada',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedoraseo',
            name='cantidad_entregada_anterior',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedoraseo',
            name='cantidad_solicitada',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedoraseo',
            name='precio_compra',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedorpersonal',
            name='cantidad_entregada',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedorpersonal',
            name='cantidad_entregada_anterior',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedorpersonal',
            name='cantidad_solicitada',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedorpersonal',
            name='precio_compra',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detallesalidadotaciónpersonal',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedidoproveedor',
            name='cantidad_entregada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoproveedor',
            name='cantidad_entregada_anterior',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoproveedor',
            name='cantidad_solicitada',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pedidoproveedor',
            name='total_pagado',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pedidoproveedoraseo',
            name='cantidad_entregada',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pedidoproveedoraseo',
            name='cantidad_entregada_anterior',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pedidoproveedoraseo',
            name='cantidad_solicitada',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedidoproveedoraseo',
            name='total_pagado',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pedidoproveedorpersonal',
            name='cantidad_entregada',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pedidoproveedorpersonal',
            name='cantidad_entregada_anterior',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pedidoproveedorpersonal',
            name='cantidad_solicitada',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedidoproveedorpersonal',
            name='total_pagado',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
