# Generated by Django 4.0.4 on 2022-07-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0061_alter_detalledevolucionpedidoproveedor_cantidad_devuelta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproveedor',
            name='solicitado',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedoraseo',
            name='solicitado',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedorpersonal',
            name='solicitado',
        ),
    ]
