# Generated by Django 4.0.4 on 2022-08-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0064_pedidoproveedor_entregado_pedidoproveedor_solicitado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedidoproveedor',
            name='cantidad_entregada',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedor',
            name='cantidad_entregada_anterior',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedor',
            name='cantidad_solicitada',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detallepedidoproveedorpersonal',
            name='cantidad_entregada_anterior',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pedidoproveedor',
            name='cantidad_entregada',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pedidoproveedor',
            name='cantidad_entregada_anterior',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pedidoproveedor',
            name='cantidad_solicitada',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedidoproveedor',
            name='solicitadoo',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Solicitado por:'),
        ),
        migrations.AlterField(
            model_name='pedidoproveedorpersonal',
            name='cantidad_entregada_anterior',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
