# Generated by Django 4.0.4 on 2022-08-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0065_alter_detallepedidoproveedor_cantidad_entregada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedidoproveedor',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='detallepedidoproveedoraseo',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='detallepedidoproveedorpersonal',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedor',
            name='total_pagado',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedoraseo',
            name='total_pagado',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedorpersonal',
            name='total_pagado',
        ),
    ]
