# Generated by Django 4.0.4 on 2022-08-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0068_alter_pacientearcoiris_segundoapellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientearcoiris',
            name='SegundoApellido',
            field=models.CharField(blank=True, default=' ', max_length=40, verbose_name='Segundo apellido'),
        ),
        migrations.AlterField(
            model_name='pacientearcoiris',
            name='SegundoNombre',
            field=models.CharField(blank=True, default=' ', max_length=40, verbose_name='Segundo nombre'),
        ),
    ]
