# Generated by Django 4.0.4 on 2022-08-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0070_alter_pacientearcoiris_fechaingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementoarcoiris',
            name='fecha_vencimiento',
            field=models.DateField(null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='elementoarcoirisaseo',
            name='fecha_vencimiento',
            field=models.DateField(null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='elementoarcoirispersonal',
            name='fecha_vencimiento',
            field=models.DateField(null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
