# Generated by Django 4.0.4 on 2022-08-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcoIris', '0072_alter_pacientearcoiris_tallacalzado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementoarcoiris',
            name='fechaElemento',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='elementoarcoirisaseo',
            name='fechaElemento',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='elementoarcoirispersonal',
            name='fechaElemento',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso'),
        ),
    ]
