# Generated by Django 4.0.4 on 2022-05-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VillaBlanca', '0003_alter_elementovillablanca_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementovillablanca',
            name='TipoProducto',
        ),
    ]
