# Generated by Django 4.0.4 on 2022-05-17 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VillaBlanca', '0006_elementovillablancaaseo_elementovillablancapersonal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementovillablancapersonal',
            options={'ordering': ['nombreElemento'], 'verbose_name': 'Inventario dotación personal', 'verbose_name_plural': 'Inventario dotación personal'},
        ),
    ]
