# Generated by Django 4.0.4 on 2022-05-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VillaBlanca', '0012_alter_elementovillablancapersonal_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementovillablanca',
            old_name='cantidad',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='elementovillablancaaseo',
            old_name='cantidad',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='elementovillablancapersonal',
            old_name='cantidad',
            new_name='stock',
        ),
    ]
