# Generated by Django 4.0.4 on 2022-05-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VillaBlanca', '0013_rename_cantidad_elementovillablanca_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientevillablanca',
            name='tiposalida',
            field=models.CharField(choices=[('traslado', 'Traslado al ICBF'), ('fallecimiento', 'Fallecimieno'), ('desertor', 'Desertor'), ('otro', 'Otro')], default='ninguna', max_length=40, null=True, verbose_name='Motivo de salida'),
        ),
        migrations.AlterField(
            model_name='pacientevillablanca',
            name='modalidad',
            field=models.CharField(choices=[('PSICOSIAL', ' Psicosocial'), ('INTELECTUAL', 'Intelectual')], default='a', max_length=40, null=True, verbose_name='Modalidad'),
        ),
    ]
