# Generated by Django 4.0.4 on 2022-06-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VillaBlanca', '0015_elementovillablanca_unidadmedida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientevillablanca',
            name='tiposalida',
            field=models.CharField(blank=True, choices=[('traslado', 'Traslado al ICBF'), ('fallecimiento', 'Fallecimieno'), ('desertor', 'Desertor'), ('otro', 'Otro')], default='ninguna', max_length=40, null=True, verbose_name='Motivo de salida'),
        ),
    ]
