# Generated by Django 4.0.4 on 2022-08-02 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0012_alter_proveedor_id'),
        ('VillaBlanca', '0017_alter_elementovillablanca_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaDotacionPersonalFORMBlanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitado_por', models.CharField(blank=True, max_length=40, null=True, verbose_name='Solicitado por:')),
                ('unidad', models.CharField(blank=True, default='Arco Iris', max_length=24, null=True, verbose_name='Unidad')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaBlanca.pacientevillablanca')),
            ],
            options={
                'verbose_name': 'Salida Dotación Personal',
                'verbose_name_plural': 'Salidas Dotación Personal',
            },
        ),
        migrations.CreateModel(
            name='PedidoProveedorPersonalBlanca',
            fields=[
                ('cantidad_solicitada', models.IntegerField(default=0)),
                ('cantidad_entregada', models.IntegerField(blank=True, default=0)),
                ('cantidad_entregada_anterior', models.IntegerField(blank=True, default=0)),
                ('fecha_pedido', models.DateField(auto_now=True, verbose_name='Fecha de solicitud')),
                ('fecha_solicitud', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('solicitadoo', models.CharField(blank=True, max_length=40, null=True, verbose_name='Solicitado por:')),
                ('recibido', models.CharField(blank=True, max_length=40, null=True, verbose_name='Recibido por:')),
                ('entregado', models.BooleanField(blank=True, null=True)),
                ('solicitado', models.BooleanField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pagado', models.IntegerField(blank=True, default=0)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaBlanca.elementovillablancapersonal')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Pedido de dotación personal',
                'verbose_name_plural': 'Pedidos de dotación personal',
            },
        ),
        migrations.CreateModel(
            name='PedidoProveedorBlanca',
            fields=[
                ('cantidad_solicitada', models.IntegerField(default=0)),
                ('cantidad_entregada', models.IntegerField(blank=True, default=0)),
                ('cantidad_entregada_anterior', models.IntegerField(blank=True, default=0)),
                ('fecha_pedido', models.DateField(auto_now=True, verbose_name='Fecha de solicitud')),
                ('fecha_solicitud', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('solicitadoo', models.CharField(blank=True, max_length=40, null=True, verbose_name='Solicitado por:')),
                ('recibido', models.CharField(blank=True, max_length=40, null=True, verbose_name='Recibido por:')),
                ('entregado', models.BooleanField(blank=True, null=True)),
                ('solicitado', models.BooleanField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pagado', models.IntegerField(blank=True, default=0)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaBlanca.elementovillablanca')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Pedido de dotación dormitorio',
                'verbose_name_plural': 'Pedidos de dotación dormitorio',
            },
        ),
        migrations.CreateModel(
            name='PedidoProveedorAseoBlanca',
            fields=[
                ('cantidad_solicitada', models.IntegerField(default=0)),
                ('cantidad_entregada', models.IntegerField(blank=True, default=0)),
                ('cantidad_entregada_anterior', models.IntegerField(blank=True, default=0)),
                ('fecha_pedido', models.DateField(auto_now=True, verbose_name='Fecha de solicitud')),
                ('fecha_solicitud', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('solicitadoo', models.CharField(blank=True, max_length=40, null=True, verbose_name='Solicitado por:')),
                ('recibido', models.CharField(blank=True, max_length=40, null=True, verbose_name='Recibido por:')),
                ('entregado', models.BooleanField(blank=True, null=True)),
                ('solicitado', models.BooleanField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pagado', models.IntegerField(blank=True, default=0)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaBlanca.elementovillablancaaseo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Pedido dotación de aseo personal ',
                'verbose_name_plural': 'Pedidos de aseo personal',
            },
        ),
        migrations.CreateModel(
            name='DevolucionPedidoProveedorPersonalBlanca',
            fields=[
                ('fecha_devolucion', models.DateField(auto_now=True)),
                ('detalle', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Devolución pedido',
                'verbose_name_plural': 'Devoluciones pedido de dotación personal',
            },
        ),
        migrations.CreateModel(
            name='DevolucionPedidoProveedorBlanca',
            fields=[
                ('fecha_devolucion', models.DateField(auto_now=True)),
                ('detalle', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Devolución pedido',
                'verbose_name_plural': 'Devoluciones pedido de dotación dormitorio',
            },
        ),
        migrations.CreateModel(
            name='DevolucionPedidoProveedorAseoBlanca',
            fields=[
                ('fecha_devolucion', models.DateField(auto_now=True)),
                ('detalle', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Devolución pedido',
                'verbose_name_plural': 'Devoluciones pedido de aseo personal ',
            },
        ),
        migrations.CreateModel(
            name='DetalleSalidaDotaciónPersonalBlanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('especificacion', models.CharField(choices=[('REPOSICIÓN POR ROTO', 'REPOSICIÓN POR ROTO'), ('REPOSICIÓN POR DETERIORO', 'REPOSICIÓN POR DETERIORO')], max_length=24, verbose_name='Especificación')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaBlanca.elementovillablancapersonal')),
                ('salida_dotacion_personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaBlanca.salidadotacionpersonalformblanca')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaBlanca.pacientevillablanca')),
            ],
            options={
                'verbose_name': 'DETALLE SALIDA',
                'verbose_name_plural': 'DETALLE SALIDA',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoProveedorPersonalBlanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField(default=0)),
                ('cantidad_entregada', models.IntegerField(blank=True, default=0)),
                ('cantidad_entregada_anterior', models.IntegerField(blank=True, default=0)),
                ('precio_compra', models.IntegerField(default=0)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaBlanca.pedidoproveedorpersonalblanca')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaBlanca.elementovillablancapersonal')),
            ],
            options={
                'verbose_name': 'DETALLE DE PEDIDO PARA DOTACIÓN PERSONAL',
                'verbose_name_plural': 'DETALLE DE PEDIDO PARA DOTACIÓN PERSONAL',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoProveedorBlanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField(default=0)),
                ('cantidad_entregada', models.IntegerField(blank=True, default=0)),
                ('cantidad_entregada_anterior', models.IntegerField(blank=True, default=0)),
                ('precio_compra', models.IntegerField(default=0)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaBlanca.pedidoproveedorblanca')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaBlanca.elementovillablanca')),
            ],
            options={
                'verbose_name': 'DETALLE DE PEDIDO PARA DOTACIÓN DE DORMITORIO',
                'verbose_name_plural': 'DETALLE DE PEDIDO PARA DOTACIÓN DE DORMITORIO',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoProveedorAseoBlanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField(default=0)),
                ('cantidad_entregada', models.IntegerField(blank=True, default=0)),
                ('cantidad_entregada_anterior', models.IntegerField(blank=True, default=0)),
                ('precio_compra', models.IntegerField(default=0)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaBlanca.pedidoproveedoraseoblanca')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaBlanca.elementovillablancaaseo')),
            ],
            options={
                'verbose_name': 'DETALLE DE PEDIDO PARA DOTACIÓN DE ASEO PERSONAL',
                'verbose_name_plural': 'DETALLE DE PEDIDO PARA DOTACIÓN DE ASEO PERSONAL',
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucionPedidoProveedorPersonalBlanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.IntegerField()),
                ('motivo', models.CharField(choices=[('PM', 'Producto en mal estado'), ('PV', 'Producto vencido')], max_length=2)),
                ('devolucion_pedido_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaBlanca.devolucionpedidoproveedorpersonalblanca')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaBlanca.elementovillablancapersonal')),
            ],
            options={
                'verbose_name': 'Detalle devolución',
                'verbose_name_plural': 'Detalle devolución',
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucionPedidoProveedorBlanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.IntegerField()),
                ('motivo', models.CharField(choices=[('PM', 'Producto en mal estado'), ('PV', 'Producto vencido')], max_length=2)),
                ('devolucion_pedido_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaBlanca.devolucionpedidoproveedorblanca')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaBlanca.elementovillablanca')),
            ],
            options={
                'verbose_name': 'Detalle devolución',
                'verbose_name_plural': 'Detalle devolución',
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucionPedidoProveedorAseoBlanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.IntegerField()),
                ('motivo', models.CharField(choices=[('PM', 'Producto en mal estado'), ('PV', 'Producto vencido')], max_length=2)),
                ('devolucion_pedido_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaBlanca.devolucionpedidoproveedoraseoblanca')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VillaBlanca.elementovillablancaaseo')),
            ],
            options={
                'verbose_name': 'Detalle devolución',
                'verbose_name_plural': 'Detalle devolución',
            },
        ),
    ]
