# Generated by Django 4.0.4 on 2022-08-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VillaBlanca', '0018_salidadotacionpersonalformblanca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedidoproveedoraseoblanca',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='detallepedidoproveedorblanca',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='detallepedidoproveedorpersonalblanca',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedoraseoblanca',
            name='total_pagado',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedorblanca',
            name='total_pagado',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedorpersonalblanca',
            name='total_pagado',
        ),
    ]
