# Generated by Django 4.0.4 on 2022-08-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VillaBlanca', '0019_remove_detallepedidoproveedoraseoblanca_precio_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoproveedoraseoblanca',
            name='entregado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoproveedoraseoblanca',
            name='solicitado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoproveedorblanca',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedidoproveedorblanca',
            name='solicitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedidoproveedorpersonalblanca',
            name='entregado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoproveedorpersonalblanca',
            name='solicitado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
