# Generated by Django 4.0.4 on 2022-08-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VillaBlanca', '0020_alter_pedidoproveedoraseoblanca_entregado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientevillablanca',
            name='SegundoApellido',
            field=models.CharField(blank=True, default=' ', max_length=40, null=True, verbose_name='Segundo apellido'),
        ),
        migrations.AlterField(
            model_name='pacientevillablanca',
            name='SegundoNombre',
            field=models.CharField(blank=True, default=' ', max_length=40, null=True, verbose_name='Segundo nombre'),
        ),
        migrations.AlterField(
            model_name='pedidoproveedorblanca',
            name='entregado',
            field=models.BooleanField(default='_'),
        ),
        migrations.AlterField(
            model_name='pedidoproveedorblanca',
            name='solicitado',
            field=models.BooleanField(default='_'),
        ),
    ]
