# Generated by Django 4.0.4 on 2022-08-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VillaBlanca', '0023_alter_pacientevillablanca_fechaingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementovillablanca',
            name='fecha_vencimiento',
            field=models.DateField(null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='elementovillablancaaseo',
            name='fecha_vencimiento',
            field=models.DateField(null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='elementovillablancapersonal',
            name='fecha_vencimiento',
            field=models.DateField(null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
