# Generated by Django 4.0.4 on 2022-08-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VillaBlanca', '0025_alter_pacientevillablanca_tallacalzado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementovillablanca',
            name='fechaElemento',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='elementovillablancaaseo',
            name='fechaElemento',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='elementovillablancapersonal',
            name='fechaElemento',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso'),
        ),
    ]
